/**
 * Manual test: RAG Ingest Pipeline (§7.1)
 *
 * Ingests a fake "Certificate Request Policy" document and verifies:
 *   1. KnowledgeDocument row created
 *   2. KnowledgeChunk rows created with non-null embeddings
 *   3. Embedding vector length matches schema dimension (1536)
 */

import { config } from "dotenv";
config();

import { prisma } from "./prisma";
import { ingestDocument } from "./rag/ingest";
import { Domain } from "@prisma/client";

// ---------------------------------------------------------------------------
// Sample institutional policy document (fake, 3 paragraphs ~800 words)
// ---------------------------------------------------------------------------
const SAMPLE_DOCUMENT = {
  title: "Certificate Request Policy — WILLUP Institution",
  domain: Domain.CERTIFICATE,
  sourceUrl: "https://willup.edu/policies/certificates",
  content: `
WILLUP Institution — Certificate Request Policy (Version 2.1, Effective August 2026)

1. SCOPE AND PURPOSE

This policy governs the process by which enrolled students and alumni may request official
certificates from WILLUP Institution. Certificates covered by this policy include, but are not
limited to: Bonafide Certificates, Transfer Certificates, Character Certificates, Transcripts,
Migration Certificates, Provisional Degree Certificates, and No Dues Certificates. The purpose
of this policy is to ensure that all certificate requests are processed in an orderly, timely,
and transparent manner, and that the authenticity of issued certificates is maintained at all
times. All requests must be submitted through the WILLUP Institutional Service Platform (WISP)
portal to ensure proper tracking and audit trail.

2. ELIGIBILITY AND REQUIRED DOCUMENTS

Students must satisfy the following eligibility criteria before submitting a certificate request:
(a) The student must be currently enrolled or have formally graduated from WILLUP Institution.
(b) All outstanding dues — including tuition fees, library fines, hostel charges, and laboratory
    breakage fees — must be cleared prior to the issuance of any certificate. A No Dues Certificate
    from all relevant departments must be attached for requests of Transfer Certificate or Migration
    Certificate.
(c) For Bonafide Certificates, the student must be currently enrolled in the current academic
    semester and must not be under any disciplinary suspension.
(d) For Transcripts and Provisional Degree Certificates, the student must have completed all
    examination requirements and received their final grade submission from all departments.
(e) The following documents are universally required for all certificate requests:
    - Valid student ID card (photocopy and original for in-person verification)
    - Completed online application form submitted via WISP
    - Applicable processing fee payment receipt (refer to the Fee Schedule, Appendix A)

3. PROCESSING TIMELINES AND ESCALATION

Standard processing timelines are as follows. Bonafide Certificates: 2 working days. Character
Certificates: 3 working days. Transcripts: 5 working days. Transfer Certificates: 7 working days
(subject to No Dues clearance). Migration Certificates: 10 working days. Provisional Degree
Certificates: 15 working days after final results declaration.

If a certificate has not been issued within the stated timeline, the student may escalate the
request within WISP. Escalation proceeds as follows:
  - First escalation: Dean of Students Office (reviewed within 2 working days of escalation).
  - Second escalation: Registrar's Office (reviewed within 3 working days of second escalation).
  - Final escalation: Vice Chancellor's Office (reserved for cases involving systemic delays
    exceeding 30 calendar days from original request date).

Urgent certificates (e.g., for visa applications or job offers) may request expedited processing
by attaching the relevant supporting document. Expedited requests are processed within 1 working
day and incur an additional fee as specified in the Fee Schedule.

Students are advised to retain all acknowledgement references generated by WISP when submitting
requests. These reference numbers are required for any follow-up queries with administrative staff.
For lost or damaged certificates, a separate re-issuance process applies — please refer to the
Re-Issuance Policy document available on the WILLUP institutional portal.
  `.trim(),
};

// ---------------------------------------------------------------------------
// Test runner
// ---------------------------------------------------------------------------

async function run() {
  console.log("=============================================================");
  console.log("  RAG Ingest Pipeline Test (§7.1)                           ");
  console.log("=============================================================\n");

  // Clean up any previous test run for this document title
  const existing = await prisma.knowledgeDocument.findMany({
    where: { title: SAMPLE_DOCUMENT.title },
  });
  if (existing.length > 0) {
    const ids = existing.map((d) => d.id);
    await prisma.$executeRaw`DELETE FROM "KnowledgeChunk" WHERE "documentId" = ANY(${ids})`;
    await prisma.knowledgeDocument.deleteMany({ where: { title: SAMPLE_DOCUMENT.title } });
    console.log(`Cleaned up ${existing.length} prior document(s).\n`);
  }

  // Run ingestion
  console.log(`Ingesting: "${SAMPLE_DOCUMENT.title}"\n`);
  const result = await ingestDocument(SAMPLE_DOCUMENT);

  // Verify KnowledgeDocument row
  const doc = await prisma.knowledgeDocument.findUnique({
    where: { id: result.documentId },
  });

  console.log("\n--- Verification ---");
  console.log(`\n[1] KnowledgeDocument row:`);
  console.log(`    id       : ${doc?.id}`);
  console.log(`    title    : ${doc?.title}`);
  console.log(`    domain   : ${doc?.domain}`);
  console.log(`    sourceUrl: ${doc?.sourceUrl}`);
  console.log(`    exists   : ${doc ? "YES ✅" : "NO ❌"}`);

  // Verify KnowledgeChunk rows
  const chunks: any[] = await prisma.$queryRaw`
    SELECT id, "documentId", content, embedding::text AS "embeddingStr"
    FROM "KnowledgeChunk"
    WHERE "documentId" = ${doc!.id}
    ORDER BY id ASC
  `;

  console.log(`\n[2] KnowledgeChunk rows:`);
  console.log(`    Count    : ${chunks.length} (Expected: ≥ 1)`);
  console.log(`    Exists   : ${chunks.length > 0 ? "YES ✅" : "NO ❌"}`);

  // Verify embedding dimension on each chunk
  let allCorrectDim = true;
  for (let i = 0; i < chunks.length; i++) {
    const embStr = chunks[i].embeddingStr;
    // pgvector returns embedding as "[x1,x2,...,xN]"
    const vals = embStr.replace(/^\[/, "").replace(/\]$/, "").split(",");
    const dim = vals.length;
    const correct = dim === 384;
    if (!correct) allCorrectDim = false;
    console.log(
      `    Chunk ${String(i + 1).padStart(2, "0")}: ${chunks[i].content.slice(0, 60).replace(/\n/g, " ")}...`
    );
    console.log(
      `             Embedding dim = ${dim} ${correct ? "✅" : "❌ (expected 384)"}, non-null = ${embStr.length > 2 ? "YES ✅" : "NO ❌"}`
    );
  }

  console.log(`\n[3] Embedding dimension summary:`);
  console.log(`    Schema expects    : 384`);
  console.log(`    Model returned    : ${result.embeddingDimension}`);
  console.log(`    All chunks match  : ${allCorrectDim ? "YES ✅" : "NO ❌"}`);

  console.log("\n=============================================================");
  const passed =
    doc !== null && chunks.length >= 1 && result.embeddingDimension === 384 && allCorrectDim;
  console.log(`  RESULT: ${passed ? "PASS ✅" : "FAIL ❌"}`);
  console.log("=============================================================\n");

  await prisma.$disconnect();
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
